# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Filter HK Airports

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['3.7']

    steps:
    - name: checkout actions
      uses: actions/checkout@v1
            
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        git checkout master

    - name: Update File
      run: |
        cd scripts
        python ./get.py

    - name: commit
      run: |
        git config --global user.email sunshinenny@icloud.com
        git config --global user.name sunshinenny
        git add .
        git commit -m "update" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
